name: Android CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Lập lịch để chạy hàng đêm vào lúc 2 giờ sáng UTC
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build và Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Thiết lập JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Cấp quyền thực thi cho Gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Kiểm tra với Lint
        run: ./gradlew lint

      - name: Chạy Unit Tests
        run: ./gradlew test

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Tạo Release
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Thiết lập JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Cấp quyền thực thi cho Gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK và Bundle
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Đọc version từ build.gradle
        id: gradle_version
        run: |
          VERSION_CODE=$(grep -o 'versionCode\s*=\s*[0-9]*' app/build.gradle.kts | grep -o '[0-9]*')
          VERSION_NAME=$(grep -o 'versionName\s*=\s*"[^"]*"' app/build.gradle.kts | grep -o '"[^"]*"' | sed 's/"//g')
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "::set-output name=version_code::$VERSION_CODE"
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Tạo Release Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ env.VERSION_NAME }}-${{ env.VERSION_CODE }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Tạo Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: Release ${{ env.VERSION_NAME }} (${{ env.VERSION_CODE }})
          draft: false
          prerelease: false

      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release-${{ env.VERSION_NAME }}-${{ env.VERSION_CODE }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release-${{ env.VERSION_NAME }}-${{ env.VERSION_CODE }}.aab
          asset_content_type: application/octet-stream

  deploy:
    name: Triển khai lên Firebase
    needs: release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tải xuống APK từ artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/

      - name: Triển khai lên Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: testers, qa
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: |
            Phiên bản mới từ branch ${{ github.ref_name }}
            Commit: ${{ github.sha }}
